### ISSUE TITLE
sap_ha_*: update module names to fqcn

### ISSUE THREAD

**Issue by ja9fuchs** [sap-linuxlab/community.sap_install#166]
Several tasks are still missing the fqcn in the module names.
Known gap to be fixed.

https://github.com/sap-linuxlab/community.sap_install/pull/161#discussion_r909578611

**Comment by sean-freeman** [comment]
@ja9fuchs I think all FQCN are added in 1.2.0 release of sap_ha_* Ansible Roles?

**Comment by ja9fuchs** [comment]
Reviewed and looks like the gaps have all been fixed.
