### ISSUE TITLE
SAP HANA Install fails XXXX  is not assigned to a local network interface

### ISSUE THREAD

**Issue by ranjithrajaram** [sap-linuxlab/community.sap_install#188]
While attempting to use sap_hana_install role, installation fails with the following message XXXX is not assigned to a local network interface

While generating the configfile.cfg for hdblcm, it uses the wrong hostname. Either one of the node installation succeeds (second node for which the configfile.cfg was generated)

To resolve this issue, had to apply the above pull request(just filed)
https://github.com/sap-linuxlab/community.sap_install/pull/187

Complete message
---
```
fatal: [dhcp200-237]: FAILED! =>
{
  "changed": true,
  "cmd": [
    "./hdblcm",
    "--ignore=check_diskspace,check_min_mem",
    "--hdbinst_server_xs_engine=off",
    "--hdbinst_server_import_content=off",
    "--configfile=/tmp/ansible.kcutby6thanaconfig/configfile.cfg",
    "-b"
  ],
  "delta": "0:00:05.065610",
  "end": "2022-07-21 11:21:01.940221",
  "msg": "non-zero return code",
  "rc": 1,
  "start": "2022-07-21 11:20:56.874611",
  "stderr_lines": [
    "Running in batch mode",
    "  IP address '10.65.200.241' (host 'dhcp200-241') is not assigned to a local network interface"
  ],
  "stdout_lines": [
    "",
    "",
    "SAP HANA Lifecycle Management - SAP HANA Database 2.00.063.00.1655123455",
    "************************************************************************",
    "",
    "",
    "Scanning software locations...",
    "Detected components:",
    "    SAP HANA Database (2.00.063.00.1655123455) in /software/hana/extracted/SAP_HANA_DATABASE/server",
    "Log file written to '/var/tmp/hdb_DB1_hdblcm_install_2022-07-21_11.20.57/hdblcm.log' on host 'dhcp200-237'."
  ]
}
```
---

**Comment by sean-freeman** [comment]
PR #187  has been reviewed and rejected, each of these Ansible Tasks are run on the remote node / are run independently. The dynamically generated config file is generated from the Jinja file inside of the Ansible Role, and pushed to `sap_hana_install_configfile_directory`. As shown in the Ansible Role defaults file, this directory is on the remote/target/managed node/s:
```
# Directory where to store the hdblcm configfile template and the Jinja2 template:
sap_hana_install_configfile_directory: "{{ sap_hana_install_software_extract_directory }}/configfiles"
```

Happy to look further into the issue if you provide more details, but your described execution is the same as the internal pipeline tests and such an error does not occur - it is very hard to debug without seeing all of your amendments from the moment you cloned/downloaded the repo. I would suggest reviewing your Ansible Inventory as a starting point though, a slip of the finger there might cause such an error you describe

**Comment by ranjithrajaram** [comment]
The only reason for hitting this problem was when the default values were used and using NFS

Looking at the default values

sap_hana_install_software_directory points to /software/hana [default value]

The path /software/hana is typically a NFS folder in most or some use cases

We generate the sap_hana_install_software_extract_directory from sap_hana_install_software_directory, so it becomes /software/hana/extracted

For configfiles, it would become /software/hana/extracted/configfiles (sap_hana_install_configfile_directory: "{{ sap_hana_install_software_extract_directory }}/configfiles")

Since /software/hana can be a NFS folder, /software/hana/extracted/configfiles can be the same on both the nodes. Without the PR, installation will fail.

If not sap_hana_install_software_extract_directory has to be mandatory and a check needs to be done before proceeding

**Comment by rhmk** [comment]
Ranjith,
the default values ensure backward compatibility to previous role behavior, where it was required to have the directory writable. Hence. the variable sap_hana_install_software_extract_directory has been introduced for precisely the case you mentioned. Please set it to a different non-NFS place and you are good to go.
Rgds
 Markus
