### ISSUE TITLE
sap_hana_install: Readme file needs update

### ISSUE THREAD

**Issue by rhmk** [sap-linuxlab/community.sap_install#191]
The Readme file in version 1.1.0 of the collection is not inline with the Readme files of sap_hana_ha_*
Please align the documentation, e.g. paraters sap_hana_sid, sap_hana_instance_number etc.

Please choose also a similar layout -- I like the overview table in sap_hana_ha_* vs. prosa in sap_hana_installl

**Comment by sean-freeman** [comment]
README of 1.1.0 contained mistaken copy/paste that suggested limited functionality, this was corrected for 1.2.0 release
