### ISSUE TITLE
Setting locale failed. warning message even after applying sap_hana_preconfigure role 

### ISSUE THREAD

**Issue by kksat** [sap-linuxlab/community.sap_install#194]
After sap_generic_preconfigure and sap_hana_preconfigure role applied successfully 

```
RUNNING HANDLER [redhat.sap_install.sap_hana_preconfigure : Let the role fail if a reboot is required] ***
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Reboot is required!"}

RUNNING HANDLER [redhat.sap_install.sap_hana_preconfigure : Show a warning message if a reboot is required] ***

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=131  changed=17   unreachable=0    failed=1    skipped=85   rescued=0    ignored=0
```

host was rebooted 

I still get warning that locale not set. 

```text
[azureuser@hana1 HDB_SERVER_LINUX_X86_64]$ sudo ./hdblcm
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
```

I consider this as an issue.

**Comment by berndfinger** [comment]
@kksat Thanks for reporting this. BTW The role name is not `sap_generic_preconfigure` but `sap_general_preconfigure`. Can you please post your reboot related variables of `sap_general_preconfigure` and `sap_hana_preconfigure here?

Regarding the locale error message when running hdblbm via sudo on the managed node, this might or might not be related.

Does the locale error also occur when executing `hdblcm` as the `<sid>adm` user?

**Comment by kksat** [comment]
"Can you please post your reboot related variables of sap_general_preconfigure and sap_hana_preconfigure here?"
