### ISSUE TITLE
sap_hana_install: sap_hana_install_software_directory needs to have execute permissions

### ISSUE THREAD

**Issue by berndfinger** [sap-linuxlab/community.sap_install#199]
Otherwise, the HANA database installation will fail with "The following software installation files are missing execute permissions:"

**Comment by berndfinger** [comment]
All directories above it also need execute permissions. So a chmod -R 0755 of the directory
`"/{{ sap_hana_install_software_directory.split(\"/\")[1] }}"` appears to be necessary.

**Comment by rhmk** [comment]
yes this is a well known feature(?) of Linux, all parent directories of an executable need to have at least the x flag set. In  a directory without x flag nothing can be executed.

**Comment by berndfinger** [comment]
Instead of modifying all directory permissions recursively from the top level (exclucing `/` of course) down to the lowest path of the software directory, we can create a list of all directories between the first level and the lowest level and then perform the chmod 755 operation on each directory, as I am showing [here](https://github.com/berndfinger/ansible-data-type-conversion/blob/main/create-list-of-all-upper-level-directories-from-a-directory-string.md) . With this method, we avoid setting these permissions for directories which are parallel to any of the paths above the software directory.
As an alternative, we can create such a list and just assert that the permissions of the upper level directories have the execute bit set. Then the execute permissions would have to be set manually and the role would have to be run again.

**Comment by berndfinger** [comment]
I ran more tests and found out that a much easier solution is to specify a `sap_hana_install_software_extract_directory` which is outside of the path of `sap_hana_install_software_directory`. The permissions of the extract directory are already modified recursively in task `SAP HANA Pre Install - Change ownership of software extract directory`.
