### ISSUE TITLE
sap_ha_install_pacemaker : SAP Pacemaker Setup - Get cluster node corosync status

### ISSUE THREAD

**Issue by rhmk** [sap-linuxlab/community.sap_install#206]
I ran into several non-deterministic failures of the above role and task because one cluster node was not immediately online. 
It might be worth retrying a few times or adding a short sleep statement to give the cluster some time to get online

**Comment by ja9fuchs** [comment]
I'm working on a complete replacement of the 2 pacemaker roles, which is using the ha_cluster role from the linux-system-roles collection. It will be interesting to repeat your tests with this one to see if similar timing issues may occur here as well.

**Comment by ja9fuchs** [comment]
That role had been replaced with `sap_ha_pacemaker_cluster`.
