### ISSUE TITLE
sap_general_preconfigure fails on SLES 15

### ISSUE THREAD

**Issue by mr-stringer** [sap-linuxlab/community.sap_install#218]
The task `Rename user sap_preconfigure variables if found, generic` within the role `sap_general_preconfigure` role fails on SLES 15 with following error:

```shell
FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {{ __sap_general_preconfigure_packagegroups }}: '__sap_general_preconfigure_packagegroups' is undefined
```

This error appears to happen because the variable `sap_general_preconfigure_packagegroups` in `roles/sap_general_preconfigure/defaults/main.yml` is set using the value of `__sap_general_preconfigure_packagegroups`.  However, when using SLES15 the variable `__sap_general_preconfigure_packagegroups` is never defined.

The same is true of the variables `__sap_general_preconfigure_envgroups` & `__sap_general_preconfigure_kernel_parameters_default`.

I will create a fix and a PR for this which is simply defining the variables in the file `roles/sap_general_preconfigure/vars/SLES_15.yml`.

**Comment by rhmk** [comment]
Great Steven, thanks. That is exactly where should go. Especially default kernel parameters could be defined in SLES15, unless you are triggering saptune instead. The other two are probably RedHat specific.
