### ISSUE TITLE
Compatibility with OS - SLES (SuSe)

### ISSUE THREAD

**Issue by picoroma** [sap-linuxlab/community.sap_install#289]
Hi!
Does these Ansible ROLEs works fine (are compatible) with other SAP certified OS (SLES & SLES for SAP) ?
Or only works with RHEL ...
Is there some example of use\run on SLES ?
THX

**Comment by sean-freeman** [comment]
Yes, better explained for imminent Ansible Collection release where documents were better clarified and SLES code updated. See note here:
https://github.com/sap-linuxlab/community.sap_install/tree/dev#operating-system-requirements

Also, GitHub Issues are not appropriate to ask questions. Please use 'Discussions'.
