### ISSUE TITLE
Template url DO NOT WORK (error 404)

### ISSUE THREAD

**Issue by picoroma** [sap-linuxlab/community.sap_install#295]
In the readme.md - the URL to the TEMPLATE examples - DO NOT WORK:
Template S/4HANA2020 input for installation

[Template S/4HANA Install](https://github.com/sap-linuxlab/community.sap_install/blob/main/playbooks/vars/s4hana/template.S4H.install)
[Template S/4HANA Restore](https://github.com/sap-linuxlab/community.sap_install/blob/main/playbooks/vars/s4hana/template.S4H.restore)
Sample S/4HANA2020 input for distributed / high availability installation (ASCS, ERS, DBCI, PAS)

[Sample S/4HANA distributed](https://github.com/sap-linuxlab/community.sap_install/blob/main/playbooks/vars/s4hana/s4hana-distributed)
Sample Solman 7.2 input installation

ABAP [Solman 7.2](https://github.com/sap-linuxlab/community.sap_install/blob/main/playbooks/vars/solman/SHA.install)
Java [Solman 7.2](https://github.com/sap-linuxlab/community.sap_install/blob/main/playbooks/vars/solman/SHA.install)

**Comment by sean-freeman** [comment]
Old format from initial commit, good spot.

Removed and replaced by clearer explanation of default parameters and samples, please see same sap_swpm README in release 1.2.0
