### ISSUE TITLE
sap_swpm - EXPORT file is not clear where should be

### ISSUE THREAD

**Issue by picoroma** [sap-linuxlab/community.sap_install#300]
Hi!
EVERY SAP (NW) product installation needs the EXPORT DVD (export file).
These are for example for SHANA 2020 file like:
S4CORE105_INST_EXPORT_1.zip .... to S4CORE105_INST_EXPORT_24.zip
In addiction there are also LANGUAGES file...

Reading the documentation is not clear where you have to put these files to perform the installation with these ansible roles...
THX

**Comment by berndfinger** [comment]
Thanks for this, we should probably update the files `README.md` and `defaults/main.yml` to clarify this.
Just put the export zip files into the folder specified by variable `sap_swpm_software_path`.

**Comment by picoroma** [comment]
Just a suggestion.
Why do not consider to use the same layout used by AWS LaunchWizard that is the ones I upload in the attach file?
![Screenshot_365](https://user-images.githubusercontent.com/23618664/209324032-c88f28ab-0c2e-41b8-9781-e9f3d6190b4e.jpg)

**Comment by sean-freeman** [comment]
For SAP S/4HANA downloads `S4CORE*`, using the download basket parameter is sufficient along with all other files and SAP SWPM 2.0 will identify the files during execution.

### For example with sap_swpm 'Default mode'...

**Vars:**
```
sap_swpm_ansible_role_mode: "default"

sap_swpm_inifile_list:
  - swpm_installation_media
  - swpm_installation_media_swpm2_hana

# Note:
# When using SWPM2 (for modern SAP products such as S/4 B/4), using .SAR files is recommended - param value should be false
# When using SWPM1 (for older SAP products), using CD Media is the only choice - param value should be true
sap_swpm_software_use_media: false

# Main path that this role will look for .SAR files
sap_swpm_software_path: /software
```

**Output inifile.param:**
- Uses this line to generate the file https://github.com/sap-linuxlab/community.sap_install/blob/main/roles/sap_swpm/templates/configfile.j2#L7

```
######
# swpm_installation_media
######
archives.downloadBasket = /software

# installation_export.archivesFolder = 

# NOTE: Specific media requirements will use format
# SAPINST.CD.PACKAGE.<media_name> = <location>

######
# swpm_installation_media_swpm2_hana
######
HDB_Software_Dialogs.useMediaCD = false
```

**Comment by sean-freeman** [comment]
The `sap_swpm` Ansible Role has no intention of organising installation media, it acts as an orchestrator for:
- 'Default mode', simplified generation of SAP SWPM inifile.params and execution
- 'Advanced mode', key:value for generation of SAP SWPM inifile.params and execution
- 'Inifile Reuse mode', direct pass-through of existing inifile.params and execution of SAP SWPM

All installation media handling is through:
- `community.sap_launchpad` Ansible Collection, with the Ansible Module `software_center_download` for SAP software downloads
- `community.sap_install` Ansible Collection, with the Ansible Module `sap_install_media_detect` for SAP installation media file organisation and automatic Ansible Variables population for `sap_hana_install` and `sap_swpm`.

**Comment by sean-freeman** [comment]
An example of the `sap_swpm` Ansible Role used for SAP S/4HANA installations including SUM post-install execution using AWS EC2 instances (given you are showing AWS Launch Wizard), is shown here:

Terraform Template for SAP S/4HANA installation using SAP Maintenance Panner stack:
https://github.com/sap-linuxlab/terraform.templates_for_sap/tree/main/sap_s4hana_single_node_install_maintenance_plan/aws_ec2_instance

> This calls the following Terraform Module wrapper around the Ansible Playbook:
> https://github.com/sap-linuxlab/terraform.modules_for_sap/tree/main/all/ansible_sap_s4hana_install_maintplan

**Comment by sean-freeman** [comment]
@picoroma if this GH Issue is not responded to within 7 days, I will close / mark it as resolved

**Comment by sean-freeman** [comment]
@picoroma I am closing this GH Issue due to lack of response, I hope the explanations solved your error with SAP SWPM
