### ISSUE TITLE
sap_general_preconfigure: `nobest` parameter is available in the `dnf` module only from ansible-core 2.11

### ISSUE THREAD

**Issue by berndfinger** [sap-linuxlab/community.sap_install#306]
So we have to replace it.
It's in https://github.com/sap-linuxlab/community.sap_install/blob/4e55919fb7145a777b9debd560b79c6c8545c92a/roles/sap_general_preconfigure/tasks/RedHat/installation.yml#L186. It came in only with commit 7fdcc136019cb4779d8e8c1463615bece9c15492 .
So we either have to no longer use the `nobest` parameter or go back to https://github.com/sap-linuxlab/community.sap_install/blob/ff5ad8941f77e5f7eaa0ef204ce3a2b438f5dd7f/roles/sap_general_preconfigure/tasks/RedHat/installation.yml#L113.

**Comment by ja9fuchs** [comment]
I suggest review of the original reason for using `nobest` in the first place. Unless there is a bug or other side effect, it should be enough to keep `state: present` (= do not install newer package versions if they are already installed, i.e. do not update).

**Comment by berndfinger** [comment]
@ja9fuchs Bug 1983749 should have all necessary information. This bug is also mentioned in the line above the task name.
