### ISSUE TITLE
sap_general_preconfigure: The role should support enabling required repos for RHEL

### ISSUE THREAD

**Issue by berndfinger** [sap-linuxlab/community.sap_install#35]
Role sap_general_preconfigure wants to install compat-sap-c++ packages, so we should better let the role also enable the required SAP repos, similar to: https://github.com/sap-linuxlab/community.sap_install/blob/7956ecd9bd289c608f6e5c0d51c5139ae9a6d349/roles/sap_hana_preconfigure/tasks/RedHat/installation.yml#L10

**Comment by rhmk** [comment]
I think that is too much, I do not like this in the other role either. My opinion is that subscription + repos is a prereq for these roles and need to be done outside, e.g. with satellite or similar. It is getting more complex, if SUSE support comes in.
I have started with a description how to use it properly in demo.sap_install repo. Still private, but I want to use this as the "underpinning" repo for my openSAP course on ansible. If you like have a look.

**Comment by rhmk** [comment]
It  may be different, if we choose to restructure the role in some kind of meta role, that only includes other roles, depending on the os and then we can have these functions as separate roles plus one role per SAP Note.

**Comment by berndfinger** [comment]
The role sap_hana_preconfigure already has such code for repos in it so it's only a move of that (currently rather complex) code out of that role and put an improved version in here, as an (default off) option until we have a role for subscription and repo handling.

**Comment by berndfinger** [comment]
Solved in pull request #42.
