### ISSUE TITLE
collection: selection of embedded system roles

### ISSUE THREAD

**Issue by rhmk** [sap-linuxlab/community.sap_install#354]
The ansible variable `ansible_role_name` holds the FQCN of the role. currently the role default is to use fedora.linux-system-roles, but this only makes sense if users use the community.sap_install collection.

Can we  change the default  to all roles that use system-roles like this:

```
sap_general_preconfigure_system_roles_collection="{{ 
 {% if  ansible_role_name == "redhat.sap_install.sap_general_preconfigure" -%}
redhat.rhel_system_roles 
{% else -%}
fedora.linux_system_roles
{% endif %}
}}"
```

Affected roles currently:
- sap_general_preconfigure
- sap_hana_install
- sap_hana_preconfigure
- sap_ha_pacemaker_cluster

PS: Not sure about the correct jinja syntax

**Comment by berndfinger** [comment]
See also https://github.com/sap-linuxlab/community.sap_install/issues/310 .

**Comment by berndfinger** [comment]
@rhmk I just added a comment to https://github.com/sap-linuxlab/community.sap_install/issues/310. Can we continue the discussion on this topic there and close the current issue?

**Comment by rhmk** [comment]
@sean-freeman #310 and #354 are more or less identical. Hence we can close this one

**Comment by rhmk** [comment]
Close as duplicate
