### ISSUE TITLE
sap_ha_pacemaker_cluster - cluster services start on boot

### ISSUE THREAD

**Issue by waorb** [sap-linuxlab/community.sap_install#364]
I've noticed that the cluster services start automatically after the boot of a failed node.

Apparently, the _ha_cluster_ system role uses variable _ha_cluster_start_on_boot_ to configure this behaviour and the default value of this variable is set to true.

I don't think it is a good idea to automatically start the cluster services on a failed node for any SAP cluster. I would suggest that this variable is at least mentioned in the README of the sap_ha_pacemaker_cluster role, so that a user of the role is aware of this and can override the setting.

Regards,
Walter

**Comment by ja9fuchs** [comment]
It's a good idea adding a reference to the Linux System Role and its many parameters, which are not explicitly used by this SAP cluster role.
