### ISSUE TITLE
sap_ha_pacemaker_cluster - sap_ha_pacemaker_cluster_fence_options

### ISSUE THREAD

**Issue by waorb** [sap-linuxlab/community.sap_install#370]
The README seems to imply that you can extend the _sap_ha_pacemaker_cluster_fence_options_ variable with any additional options you need.
For example, in our environment, we need the two additional options at the bottom of this variable definition:
````
sap_ha_pacemaker_cluster_fence_options:
  pcmk_reboot_retries: 4
  pcmk_reboot_timeout: 600
  power_timeout: 240
  pcmk_monitor_timeout: 600
  pcmk_status_timeout: 60
````

However, when I try to run the role, it fails in the argument validation task:

````
TASK [redhat.sap_install.sap_ha_pacemaker_cluster : Validating arguments against arg spec 'main' - SAP HA automated cluster setup requirements]
fatal: [wo-cl-h01-1]: FAILED! => {"argument_errors": ["sap_ha_pacemaker_cluster_fence_options.pcmk_monitor_timeout, sap_ha_pacemaker_cluster_fence_options.pcmk_status_timeout. Supported parameters include: pcmk_reboot_retries, pcmk_reboot_timeout, power_timeout."], "argument_spec_data": {"ha_cluster": {"description": ["Optional _**host_vars**_ parameter - if defined it must be set for each node.", "Dictionary that can contain various node options for the pacemaker cluster configuration."
````
I suspect the problem is, that in _meta/argument_specs.yml_ , the variable _sap_ha_pacemaker_cluster_fence_options_ is defined with an additional **_options_** parameter. And within that options parameter, the three default pcmk.... option are defined.
It looks like whenever the options parameter is defined, the argument check validates whether the supplied parameters match one of the options.
In my case, it fails as the _pcmk_monitor_timeout_ and _pcmk_status_timeout_ parameters are not defined in the options parameter.

As soon as I take those two parameters out from the variable definition, the validation check runs without a problem.

The counter-example is the _sap_ha_pacemaker_cluster_cluster_properties_ variable. I've added another option to that variable and this passes the check just fine. 
The difference seems to be that this variables doesn't have the additional _options_ parameter defined in the _argument_specs.yml_ file

**Comment by ja9fuchs** [comment]
Another good catch, thanks!

You are correct, the parameter can be enhanced with custom options, which should be added correctly to the resource configuration. 
argument_specs validation is indeed very strict and will not accept more options than those described.

**Comment by ja9fuchs** [comment]
Confirmed to be fixed.
