### ISSUE TITLE
sap_install_media_detect: Also rename any zip file without extension

### ISSUE THREAD

**Issue by berndfinger** [sap-linuxlab/community.sap_install#405]
We are renaming rar files but we better also rename zip files so that all files have proper endings.

**Comment by berndfinger** [comment]
and also rename and self-extracting rar file (=the first file in a rar series) to .exe.

**Comment by sean-freeman** [comment]
Although it breaks common practice for self-extracting RAR to use `.exe`, would it be "better practice" in our situation to use `.rar.exe` ?

It should have no usable impact even if the file was transferred to a Windows OS - but would be clearer.

**Comment by berndfinger** [comment]
See https://github.com/sap-linuxlab/community.sap_install/issues/408 .

**Comment by berndfinger** [comment]
With #408 and #406, we can close this issue now.
