### ISSUE TITLE
sap_install_media_detect: Support skipping zip and rar extraction if `*_extracted` directory already exists

### ISSUE THREAD

**Issue by berndfinger** [sap-linuxlab/community.sap_install#428]
By using a new role parameter, we could optionally skip the extraction phase for those files for which an `*_extracted` directory already exists. The default behavior would be to first remove the `*_extracted` directory before the extraction phase.
The current behavior is to attempt to extract each file, causing the role to wait forever in case the unzip command finds an existing destination file.

**Comment by ja9fuchs** [comment]
Removing is the clean way. A parameter to choose overwriting files would be nice, to speed up re-runs. :)

**Comment by berndfinger** [comment]
Proposed name of the variable (type `boolean`): `sap_install_media_detect_remove_extracted_dirs_initially`

**Comment by sean-freeman** [comment]
Outcomes and execution methods:

- Outcome 1: Extract files again
    - Execution Method 1: Extract files and overwrite existing file
    - Execution Method 2: Remove directory of files, extract files
- Outcome 2: Skip

In either execution method, the files are still processed, extracted and written to disk. I don't believe unrar or unzip will look at a checksum, and choose not to overwrite if the file is identical. Therefore both execution methods when extracting the files again, would take approximately the same time to execute.

Given this - in my opinion, I would opt for method # 2 for clarity to end user:

- Ansible Task "Subdirectory contents check and purge" would show as `skipped` when blank or when variable is set to skip, and would remove files if already exists.
- Ansible Task "Extract" would extract when blank, or skip if directory already contains files

**Comment by berndfinger** [comment]
Solved by PR #434 .
