### ISSUE TITLE
sap_hana_install: arguments_spec.yml breaks backward compatibility

### ISSUE THREAD

**Issue by rhmk** [sap-linuxlab/community.sap_install#436]
The current arguments spec file requires the role-specific variables to be set, otherwise the role breaks.

For better readability, we decided to set `sap_hana_sid` and `sap_hana_instance_number` to be used for all roles. The main.yml file of this role sets `sap_hana_install_sid` and `sap_hana_install_number`, using the previous variables.

Furthermore, nolog is set to true., which does not sound right.

**Comment by berndfinger** [comment]
As the variables are already verified in file `tasks/main.yml`, I am fine with setting:
```
required: false
```
in `meta/argument_specs.yml` and also I agree that the `no_log` line can be removed from that file.

**Comment by rhmk** [comment]
Did run a test. https://github.com/sap-linuxlab/community.sap_install/pull/438 perfectly fixes the problem. This issue can be closed with the next release to galaxy

**Comment by berndfinger** [comment]
Part of release 1.3.1 on GitHub and Galaxy.
