### ISSUE TITLE
Urgent: sap_hana_preconfigure: need to add RHEL 8.8 to supported releases

### ISSUE THREAD

**Issue by rhmk** [sap-linuxlab/community.sap_install#497]
according to https://me.sap.com/notes/2235581 RHEL 8.8 is supported, but not in the list

**Comment by rhmk** [comment]
change is already merged to dev

**Comment by rhmk** [comment]
@berndfinger : can you please check if kernel min release or anything else need to be added for the role to properly support RHEL 8.8

**Comment by berndfinger** [comment]
> @berndfinger : can you please check if kernel min release or anything else need to be added for the role to properly support RHEL 8.8
Yes, we need a minimum RHEL kernel version for RHEL 8.8 as per SAP note https://me.sap.com/notes/2777782 v.47. I'll create a PR for this.

**Comment by berndfinger** [comment]
Solved by https://github.com/sap-linuxlab/community.sap_install/commit/c06ece88dc8d1276ec2aa611a12c1aaaf93c69ff and PR #501
