### ISSUE TITLE
Role sap_ha_pacemaker_cluster and __sap_ha_pacemaker_cluster_vip_resource_id variable

### ISSUE THREAD

**Issue by Baboulinet-33** [sap-linuxlab/community.sap_install#512]
Hello,

I want to play role `sap_ha_pacemaker_cluster` for ASCS and ERS.
What is the purpose of the variable `__sap_ha_pacemaker_cluster_vip_resource_id` ?
Here link: [__sap_ha_pacemaker_cluster_vip_resource_id](https://github.com/sap-linuxlab/community.sap_install/blob/5b920752aa818fcd9fe96ce740bffaa314baf99e/roles/sap_ha_pacemaker_cluster/tasks/construct_vars_vip_resources_default.yml#L19C39-L19C39)

The playbook failed because the variable is undefined

**Comment by ja9fuchs** [comment]
Thanks for reporting! This bad variable reference slipped through testing after the previous VIP resource logic improvements.
