### ISSUE TITLE
sap_swpm: cross repository dependency to sap_launchpad

### ISSUE THREAD

**Issue by marcelmamula** [sap-linuxlab/community.sap_install#547]
sap_swpm role is currently expecting python3-pip (ansible.builtin.pip) to be present on target server (not execution node).
This package is not installed using preconfigure roles and dependency is not clearly stated.
Pip is also not present in base images for SLES or RHEL.

Issue does not appear if sap_launchpad download is executed because it is installed here https://github.com/sap-linuxlab/community.sap_launchpad/blob/85d6cb9215ede07aaad98036939ad4f0c2310757/playbooks/sample-download-install-media.yml#L13

Proposal in separate PR: Add python3-pip into sap_swpm role.

Affected line
https://github.com/sap-linuxlab/community.sap_install/blob/5b920752aa818fcd9fe96ce740bffaa314baf99e/roles/sap_swpm/tasks/swpm.yml#L35

**Comment by berndfinger** [comment]
@marcelmamula Thanks for your suggestion. I agree that we cannot assume that customers would have executed the `sap_launchpad` role before running `sap_swpm`. So implementing the installation of `python3-pip` in `sap_swpm` is advisable.
Note: I will soon spend some time on trying to remove the dependency on the `community.general.pids` Ansible module. Once successful, we likely do not need `psutil` (and `python3-pip`) any more. We can then remove the package installation of `python3-pip` again.

**Comment by sean-freeman** [comment]
Agree with @marcelmamula regarding this oversight.

Agree with @berndfinger also, the `community.general.pids` Ansible Module usage was intended as a short-term fix to watch the `sapinst` process (using shell `ps` to watch was not stable enough and would result in early exit of the Ansible Task).
