### ISSUE TITLE
sap_anydb_install_oracle: Use variable for finding log files in Oracle DB install

### ISSUE THREAD

**Issue by rnozaki** [sap-linuxlab/community.sap_install#587]
The task [Oracle DB - Find log files] under the sap_anydb_install_oracle has the path /oraInventory hardcoded, but the role allow to use a variable (sap_anydb_install_oracle_inventory_central) to define a custom location.

If a custom location is used, the task fails as it is using a hardcoded value.

```
- name: Oracle DB - Find log files
  become_user: root
  ansible.builtin.shell: |
    ls -1 /oraInventory/logs/InstallActions*/installActions*
  register: __sap_anydb_install_oracle_logs
```

**Comment by sean-freeman** [comment]
PR merged, closing issue
