### ISSUE TITLE
sap_vm_preconfigure: Wrong role name for sap_general_preconfigure in README.md

### ISSUE THREAD

**Issue by berndfinger** [sap-linuxlab/community.sap_install#609]
The README.md file still shows the previous role name, sap_preconfigure.

**Comment by Wabri** [comment]
The sap_vm_preconfigure no longer exists, we should close this!

**Comment by sean-freeman** [comment]
Good call @Wabri, this was moved to `sap_infrastructure` Ansible Collection in PR #632
