### ISSUE TITLE
sap_hana_preconfigure: Catch SELinux disabled

### ISSUE THREAD

**Issue by berndfinger** [sap-linuxlab/community.sap_install#641]
On a system which is currently `SELinux` `disabled`, the task https://github.com/sap-linuxlab/community.sap_install/blob/7720d7a025a8cca1c7dde23b46df8174e2fdf0fc/roles/sap_hana_preconfigure/tasks/RedHat/generic/configure-selinux.yml#L3 might fail because the `lsr/selinux` role cannot perform all required operations in this case. 

Maybe it is possible to add additional conditions similar to https://github.com/sap-linuxlab/community.sap_install/blob/7720d7a025a8cca1c7dde23b46df8174e2fdf0fc/roles/sap_general_preconfigure/tasks/RedHat/generic/configure-selinux.yml#L109 without adding too many more tasks.

Note: This behavior can only occur if a system is running in SElinux status `disabled`. This should be a very rare case because the default of a freshly installed RHEL system is to run in SElinux status `enforcing`.

**Comment by sean-freeman** [comment]
If this does occur when `SELinux` is in status `disabled` already, then this would probably impact the majority of OS Images / VM Templates used with Hypervisor platforms; as an administrator will likely prepare the OS Image for SAP with this disabled.

**Comment by berndfinger** [comment]
On a system which is running with SELinux **disabled**, a playbook which calls `sap_general_preconfigure` and `sap_hana_preconfigure` with the default SELinux role parameter settings (`*_modify_selinux_labels: true`) will change the system from **disabled** to **permissive** (which will trigger a reboot), then reboot after the role `sap_general_preconfigure` has completed, then continue with the role `sap_hana_preconfigure`. At that time, the system is no longer running with SELinux **disabled**, so the task https://github.com/sap-linuxlab/community.sap_install/blob/7720d7a025a8cca1c7dde23b46df8174e2fdf0fc/roles/sap_hana_preconfigure/tasks/RedHat/generic/configure-selinux.yml#L3 cannot fail.

The missing piece here is that the role `sap_general_preconfigure` will not configure the SELinux file contexts because the related task had been skipped. But this is a different topic.

The case mentioned in the initial note of this issue won't happen if the playbook contains both roles.

**Comment by berndfinger** [comment]
(However, it is worth fixing this issue - just in case the role `sap_hana_preconfigure` will be run separately.)

**Comment by berndfinger** [comment]
Fixed in #645.
