### ISSUE TITLE
collection/workflows: Run ansible-test sanity for each pull request

### ISSUE THREAD

**Issue by berndfinger** [sap-linuxlab/community.sap_install#648]
For keeping the code clean, for not overlooking anything, and because the ansible sanity checking workflow run does not take very long, we should better do the sanity checking with each pull request and not just once per week.

**Comment by Wabri** [comment]
@berndfinger will you solve it? Or I can take it?

**Comment by berndfinger** [comment]
@Wabri Thanks, feel free to take it!
