### ISSUE TITLE
sap_swpm: prepare_software changes ownership of files every time it runs

### ISSUE THREAD

**Issue by rnozaki** [sap-linuxlab/community.sap_install#663]
In the task prepare_software.yml there are 3 subtasks that will run to change the ownership of the SAP media directory and files, every time it runs.

This adds extra time on the execution (in one customer the media is from NFS, so it takes 15+ minutes more to run).

When running the automation multiple times on the same servers, or also on different servers, it gets to a point where we know that ownership was already set.

Can we make these subtasks optional? So if the user knows that the ownership was already validated/adjusted, they can run the automation with a flag that will prevent the execution of the redundant ownership change.

**Comment by berndfinger** [comment]
@rnozaki I agree, this behavior needs to be changed.
FYI - somehow similar issue but for role sap_hana_install: https://github.com/sap-linuxlab/community.sap_install/issues/199

**Comment by rnozaki** [comment]
OK, with the PR that I sent, the default behavior would not be changed.

So if someone knows for sure that they do not need to redo the ownership change (after having done it initially), then they can intentionally set the flag to false to avoid the redundant processing.

**Comment by berndfinger** [comment]
Solved in #665.
