### ISSUE TITLE
sap_*_preconfigure: Tests with ansible parameter -i instead of -l

### ISSUE THREAD

**Issue by streitd** [sap-linuxlab/community.sap_install#671]
Switching from using the `-l` parameter to `-i` in tests scripts running ansible-playbook command. No more need to specify hosts in `/etc/ansible/hosts` each time.

**Comment by berndfinger** [comment]
@streitd Sorry, I found your commit only after I provided mine. But mine also has the fix for the test programs in `sap_hana_install`. ;-)

**Comment by berndfinger** [comment]
Solved in https://github.com/sap-linuxlab/community.sap_install/pull/680. Also in https://github.com/sap-linuxlab/community.sap_install/pull/672 but that one had been opened against the main tree.
@streitd Thanks for reporting and fixing this!
