### ISSUE TITLE
sap_general_preconfigure: false duplicates in /etc/hosts due to partial matching

### ISSUE THREAD

**Issue by ja9fuchs** [sap-linuxlab/community.sap_install#696]
Related to #132, but an issue on its own and while comments are not there on fresh end-to-end installations, the following is a problem that can occur anytime.

The `awk` search for duplicate IPs in `/etc/hosts` is not restricted to match the whole word. That leads to partial matches and a false error that ends the play and is an issue when IPs are randomly assigned during system deployment in a specified range, e.g. in cloud instances.

Example: IP check for `10.1.1.12` will conflict with an existing entry for `10.1.1.120`.

File: `roles/sap_general_preconfigure/tasks/RedHat/generic/assert-etc-hosts.yml`

Code: `awk 'BEGIN{a=0}/{{ sap_general_preconfigure_ip }}/{a++}END{print a}' /etc/hosts`

Suggestion to only match the whole IP of an actual entry (no comment):
Add `^` and `\s` to indicate the word ending.
`awk 'BEGIN{a=0}/^{{ sap_general_preconfigure_ip }}\s/{a++}END{print a}' /etc/hosts`

Edit: `\w` didn't work for other entries, but `\s` does.

**Comment by berndfinger** [comment]
@ja9fuchs Thanks for reporting this. I already successfully tested with `\s`. See also https://github.com/sap-linuxlab/community.sap_install/blob/d36cc155dc82fdb1848b1f36d6dbbedb9d06a3ab/roles/sap_general_preconfigure/tasks/RedHat/generic/configure-etc-hosts.yml#L57 and https://github.com/sap-linuxlab/community.sap_install/blob/d36cc155dc82fdb1848b1f36d6dbbedb9d06a3ab/roles/sap_maintain_etc_hosts/tasks/update_host_present.yml#L86 .

**Comment by berndfinger** [comment]
Fixed in #697, regression #736 fixed in #737.
