### ISSUE TITLE
sap_install_media_detect: Kernel info files in download basket incorrectly counted as kernel duplicates

### ISSUE THREAD

**Issue by rob0d** [sap-linuxlab/community.sap_install#703]
As discussed with @berndfinger, when SAP Download Manager is used to download the basket, it will download the actual files as well as info files for most SAR file with the same name, but no suffix:
```
ls SAPEXE*
SAPEXE_51-70007807      SAPEXEDB_51-70007806
SAPEXE_51-70007807.SAR  SAPEXEDB_51-70007806.SAR
```
These files are correctly detected by the sapfile script:
```
# ./sapfile  -e --lsar_file=/usr/bin/unrar --sapcar_file=/install/s4hana/2023sp01/SAPCAR.EXE /install/s4hana/2023sp01/SAPEXE_51-70007807.SAR
/install/s4hana/2023sp01/SAPEXE_51-70007807.SAR;sap_kernel;sap_swpm_download_basket;none;sapcar;n;n
# ./sapfile  -e --lsar_file=/usr/bin/unrar --sapcar_file=/install/s4hana/2023sp01/SAPCAR.EXE /install/s4hana/2023sp01/SAPEXE_51-70007807
/install/s4hana/2023sp01/SAPEXE_51-70007807;sap_kernel;sap_swpm_download_basket;none;other;n;n
```
However the code that checks for duplicates in  roles/sap_install_media_detect/tasks/prepare/create_file_list_phase_2.yml e.g.
- name: SAP Install Media Detect - Prepare - Assert that exactly one SAP Kernel DB independent is present
does not take this into account.

Pull request was created with fixed for SAPEXE, SAPEXEDB, igs, igshelper and WebDispl.
I have not tested all options as I only have S/4 HANA installation, so I am not sure if similar fix will be needed for other file types.

**Comment by berndfinger** [comment]
Fixed in https://github.com/sap-linuxlab/community.sap_install/pull/702 .
