### ISSUE TITLE
Workflows: Sanity workflow aborts with "invalid escape sequence"

### ISSUE THREAD

**Issue by berndfinger** [sap-linuxlab/community.sap_install#715]
See https://github.com/sap-linuxlab/community.sap_install/actions/runs/8724773730/job/23936134891?pr=697.
Related lines appear to be:
https://github.com/sap-linuxlab/community.sap_install/blob/b3d9b9ab6933fab04acc7e72644e15732a58d468/workflows/check_outdate_deps/check_deps.py#L29
https://github.com/sap-linuxlab/community.sap_install/blob/b3d9b9ab6933fab04acc7e72644e15732a58d468/workflows/check_outdate_deps/check_deps.py#L44
https://github.com/sap-linuxlab/community.sap_install/blob/b3d9b9ab6933fab04acc7e72644e15732a58d468/workflows/check_outdate_deps/check_deps.py#L254
@Wabri Can you please have a look?

**Comment by berndfinger** [comment]
@Wabri Please also fix the spell error (as reported in https://github.com/sap-linuxlab/community.sap_install/actions/runs/8724773724/job/23936134820?pr=697, there is only a singular form of the noun `data`) in:
https://github.com/sap-linuxlab/community.sap_install/blob/b3d9b9ab6933fab04acc7e72644e15732a58d468/workflows/check_outdate_deps/check_deps.py#L229
https://github.com/sap-linuxlab/community.sap_install/blob/b3d9b9ab6933fab04acc7e72644e15732a58d468/workflows/check_outdate_deps/check_deps.py#L236

**Comment by Wabri** [comment]
Yes 👍
