### ISSUE TITLE
collection: Rename all sample playbooks to no longer contain dashes

### ISSUE THREAD

**Issue by berndfinger** [sap-linuxlab/community.sap_install#726]
Otherwise, calling a playbook, like the one named `sample-sap-hana-preconfigure.yml`, as in:
```
$ ansible-playbook community.sap_install.sample-sap-hana-preconfigure
```
will fail with an error message which does not immediately show the root cause:
```
ERROR! the playbook: community.sap_install.sample-sap-hana-preconfigure could not be found
```

**Comment by rhmk** [comment]
Playbooks in this directory can be called directly, when they do not contain dashes. 
Hence we should recreate the playbooks with the following features:

- flexible hosts entry, which defaults to localhost
- interactive questioning for minimum viable parameters (vars_prompt), if not defined with -e on the cli
- printout of help page / link to all possible parameters

**Comment by rhmk** [comment]
Wishlist of playbooks, please add more

- sap_hana_preconfigure (run's roles to prepare for SAP HANA)
- sap_netweaver_preconfigure (run's roles to prepare for SAP_NETWEAVER)
- sap_hana_install (run's roles to install SAP HANA)
- optional: sap_s4hana_install (run's role to install S4 HANA)
- optional: sap_hana_uninstall
- optional: sap_s4hana_uninstall

**Comment by berndfinger** [comment]
Let's leave the names of the current playbooks unchanged because those are not meant to be called with the fully qualified name. And we will just add new ones which then can be called with the fully qualified name.
