### ISSUE TITLE
sap_general_preconfigure: dig command

### ISSUE THREAD

**Issue by sean-freeman** [sap-linuxlab/community.sap_install#743]
sap_general_preconfigure: dig command

Ansible Task `Check resolv.conf settings` requires the FQDN to retrieve the A Record (i.e. `sap-hana.example.com`). Otherwise a CNAME Record is required if wanting to use short name only (i.e. `sap-hana`), which if I recall correctly is not recommended by SAP.

Ansible Task `Check dns reverse settings` requires a PTR Record.

In both cases I would suggest clearer Ansible Task names:
- `Check DNS Resolver in resolv.conf contains A Record for host`
- `Check DNS Resolver in resolv.conf contains reverse PTR Record for host`

I would suggest appending using the full `hostname -f` value for the first Ansible Task

**Comment by berndfinger** [comment]
Solved by https://github.com/sap-linuxlab/community.sap_install/pull/765.
