### ISSUE TITLE
sap_swpm: hdbuserstore default entry changed incorrectly in the post installation steps

### ISSUE THREAD

**Issue by rob0d** [sap-linuxlab/community.sap_install#747]
Hi guys, over the past few weeks I was trying to do installs in a more secure way with different passwords for different users (rather than the same for everything) and I've found a few problems :). Some may be bugs in swpm and I am still investigating that. Presumably it will be best to create separate issues and pull requests for each? So this is the first one.

[SAP SWPM Post Install - Enforce Connection Info in SAP HANA Client hdbuserstore](https://github.com/sap-linuxlab/community.sap_install/blob/dev/roles/sap_swpm/tasks/post_install.yml#L44C1-L58C86) is inserting incorrect password for the SAPHANADB user. This completely kills the system as the hdbuserstore is changed after SAP started (so it's not obvious), but when it's restarted or new connections are made the SAPHANADB user gets locked and the ABAP instances obviously die/hang.

I don't understand why is this step required? hdbuserstore is correctly populated by SWPM and everything works. How does it relate to host agent?

Anyway, `sap_swpm_db_schema_abap_password`  (SAPHANADB schema password) should be used instead of `sap_swpm_db_system_password` (user SYSTEM password).

**Comment by rob0d** [comment]
Pull request #748

**Comment by sean-freeman** [comment]
@rob0d Original code is from PR #446 describing `hdbuserstore` incorrectly populated by SWPM using the IP Address instead of Hostname . Your PR #748 addresses the password problem identified, and has been merged - please re-run a test and use any of the commands I showed in the PR to validate at will.

If everything is taken care of, please close this GH Issue

**Comment by sean-freeman** [comment]
@rob0d Let's consolidate the discussion in one place and close this GH Issue?
