### ISSUE TITLE
Idempotency is missing when testing with molecule.

### ISSUE THREAD

**Issue by glavoix** [sap-linuxlab/community.sap_install#752]
Dear Community,

We are in the process of implementing two roles from your collection:
_ sap_general_preconfigure
_ sap_hana_preconfigure

They are working as expected however we are running integration tests using molecule and the testing fails
during the idempotency phase as some role use OS command (like yum or sysctl), and therefore adding condition
 -> "changed_when: false" 
should be used for those specific task. Another way is to tag them with molecule-idempotence-notest as explained here:
https://ansible.readthedocs.io/projects/molecule/configuration/#ansible

Here are a few tasks where we found that case:
https://github.com/sap-linuxlab/community.sap_install/tree/main/roles/sap_hana_preconfigure/tasks/sapnote/2382421.yml#L70
https://github.com/sap-linuxlab/community.sap_install/tree/main/roles/sap_hana_preconfigure/tasks/sapnote/3024346.yml#L27

https://github.com/sap-linuxlab/community.sap_install/tree/main/roles/sap_general_preconfigure/tasks/RedHat/generic/configure-kernel-parameters.yml#L15

https://github.com/sap-linuxlab/community.sap_install/tree/main/roles/sap_general_preconfigure/tasks/RedHat/installation.yml#L118

Would it be possible to add such a tag or condition ?

Thanks,
Guillaume

**Comment by kksat** [comment]
@glavoix 

You might have a look into roles general_preconfigure and hana_preconfigure in sap.sap_operations collection

https://galaxy.ansible.com/ui/repo/published/sap/sap_operations/content/?showing=role

Documentation is here: 
https://docs.galaxy.saponrhel.org/collections/sap/sap_operations/hana_preconfigure_role.html#ansible-collections-sap-sap-operations-hana-preconfigure-role

https://docs.galaxy.saponrhel.org/collections/sap/sap_operations/general_preconfigure_role.html#ansible-collections-sap-sap-operations-general-preconfigure-role

Roles are idempotent and tested with molecule (see documentation how reboot is handled)

cc @berndfinger @sean-freeman

**Comment by berndfinger** [comment]
Hi @glavoix - please have a look at https://github.com/sap-linuxlab/community.sap_install/pull/807.

**Comment by berndfinger** [comment]
Solved in https://github.com/sap-linuxlab/community.sap_install/pull/807.
