### ISSUE TITLE
sap_general_preconfigure/RHEL: revert to using the package module for installing package groups

### ISSUE THREAD

**Issue by berndfinger** [sap-linuxlab/community.sap_install#755]
After the end of support of RHEL 8.1, we should now be able to switch back to using the package module for installing package groups instead of running `yum install {{ sap_general_preconfigure_packagegroups | join(' ') }} --nobest --exclude=kernel* -y"` in task `Ensure that the required package groups are installed, RHEL 8 and RHEL 9`

**Comment by sean-freeman** [comment]
Can we not retin the task with a when to only run on RHEL 8.1 ?

**Comment by berndfinger** [comment]
> Can we not retain the task with a when to only run on RHEL 8.1 ?

OK for me. I'll prepare a corresponding PR.

**Comment by berndfinger** [comment]
Solved in https://github.com/sap-linuxlab/community.sap_install/pull/758.
