### ISSUE TITLE
sap_general_preconfigure: DNS check ignores A/PTR record insonsistencies

### ISSUE THREAD

**Issue by rob0d** [sap-linuxlab/community.sap_install#766]
Currently the check of A and PTR records in [check-dns-name-resolution.yml](roles/sap_general_preconfigure/tasks/RedHat/generic/check-dns-name-resolution.yml) is set to ignore all errors. There is a message in the log, but as the playbook finishes happily this is easily missed.
I am suggesting to change the three tasks to fail if the test isn't successfull.
Also changed the text of the tasks to make it clearer what is failing.
Pull Request #765 .

**Comment by sean-freeman** [comment]
Relates to #743

**Comment by rob0d** [comment]
Oh yes. I've used slightly different text to yours.

**Comment by berndfinger** [comment]
Solved by PR https://github.com/sap-linuxlab/community.sap_install/pull/765.
