### ISSUE TITLE
collection: Add SPDX headers to all files of the collection

### ISSUE THREAD

**Issue by berndfinger** [sap-linuxlab/community.sap_install#777]
We discussed among contributors if we want SPDX headers, and voted unanimously for adding a one-line SPDX header to all the files of the collection.

See `SPDX short form identifier` in https://spdx.dev/learn/handling-license-info/ for examples and more information.

**Comment by Wabri** [comment]
Sorry @berndfinger I didn't see that you already assigned yourself! Do you want me to close that pr?

**Comment by berndfinger** [comment]
Solved in #778 . Thanks for this @Wabri !
