### ISSUE TITLE
sap_hana_preconfigure/RHEL: tsx kernel parameters not set for RHEL9

### ISSUE THREAD

**Issue by GutiPerez** [sap-linuxlab/community.sap_install#793]
Hello

In [SAP Note 3108302, Recommended OS Settings for RHEL 9](https://me.sap.com/notes/3108302), it is stated under section "Enable TSX (Intel Platform only)", that from RHEL 8.3 onwards, we need to add "tsx=on" kernel parameter to the grub command line.

Nevertheless, [here](https://github.com/sap-linuxlab/community.sap_install/blob/c1b479ef710f0f0803a5a081eafd621465c86d4b/roles/sap_hana_preconfigure/tasks/RedHat/generic/enable-tsx.yml#L15), you are adding it ONLY for RHEL 8.

As a suggestion, you could change the line above for this one:
`ansible_distribution_major_version|int >= 8`

Thanks in advance

**Comment by glavoix** [comment]
Very useful ! Thanks :)

**Comment by berndfinger** [comment]
Your're welcome! PR is now merged.
