### ISSUE TITLE
sap_hana_preconfigure: Support for RHEL 8.10

### ISSUE THREAD

**Issue by xenobiot** [sap-linuxlab/community.sap_install#867]
Hello,

probably you already know that HANA 2.0 (SAP HANA 2.0 SPS05 Revision 59.12 and SAP HANA 2.0 SPS07 Revision 77 and higher) is already supported on RHEL 8.10.        
Please see SAP OSS Note [2235581](https://me.sap.com/notes/2235581)
When will Ansible role sap_hana_preconfigure support RHEL 8.10, too?
https://github.com/sap-linuxlab/community.sap_install/blob/main/roles/sap_hana_preconfigure/vars/RedHat_8.yml#L10

Meanwhile we are executing the role using these parameters:
```yml
sap_hana_preconfigure_min_rhel_release_check: no    
sap_hana_preconfigure_min_package_check: no
```
Thank you very much.
Best regards,
Andrea

**Comment by berndfinger** [comment]
> Note: The current version of the role `sap_hana_preconfigure` should only issue a warning message when being run against a RHEL 8.10 managed node, and not fail. However, it will not update the kernel to `4.18.0-553.16.1.el8_10`. We recommend to update packages to the latest level for new SAP on RHEL systems, which would also ensure that the kernel will be on a level later than this.

Correction: Updating the system will ensure that the kernel is on the **same or higher** kernel level than the one mentioned above.
