### ISSUE TITLE
sap_hana_install: hana_exists.yml false detection of existing installations

### ISSUE THREAD

**Issue by waorb** [sap-linuxlab/community.sap_install#94]
hana_exists.yml checks for directories like `/hana/shared/SID` and `/usr/sap/SID` and fails if those directories aready exist.
This leads to false detections in enviroments where the SID is used as part of the filesystem mountpoint, e.g.

```
# df -h | egrep "HC1|Filesystem"
Filesystem                            Size  Used Avail Use% Mounted on
/dev/mapper/hc1usrsapvg-hc1usersaplv   32G   66M   32G   1% /usr/sap/HC1
/dev/mapper/hc1logvg-hc1loglv          48G  6.4G   42G  14% /hana/log/HC1
/dev/mapper/hc1sharedvg-hc1sharedlv    64G   50G   15G  77% /hana/shared/HC1
/dev/mapper/hc1datavg-hc1datalv        64G   18G   47G  28% /hana/data/HC1
v-srv1:/srv/backup/hana/HC1           2.4T 1021G  1.4T  43% /hana/backup/HC1
```
This is for example needed when you want to install more than one HANA system on a server.

Checking the existence of an HANA installation based on directory names is also somewhat problematic. During a manual installation, one can also override the suggested defaults for various directories. This isn't really recommended, but it is not forbidden either.

An alternative could be to check for the existence of `/usr/sap/hostctrl/exe/saphostctrl` and then use `saphostctrl` to check the already installed instances:

```
# /usr/sap/hostctrl/exe/saphostctrl -function ListInstances
 Inst Info : HC1 - 00 - hc1na1 - 753, patch 625, changelist 2007209
```

**Comment by berndfinger** [comment]
What if we used `./extracted/SAP_HANA_DATABASE/hdblcm --list_systems` from the software directory (e.g. /software/hana)? Then we would not have to rely on saphostctrl. However, we would have to extract the files from the IMBD*.SAR file first not yet done.
BTW I just tested on my freshly installed HANA server:
`# /usr/sap/hostctrl/exe/saphostctrl -function ListInstances`
and got:
`Error: NIECONN_REFUSED (Connection refused), NiRawConnect failed in plugin_fopen()`
using the `root` user and also using the `<sid>adm` user. I have not tried to find out what is causing it but the other method at least appears to be more reliable.

**Comment by DominikDunst** [comment]
We have the same problem with the existing directories when installing HANA on NFS.
Because we have already extracted Archives, I would support the proposal with hdblcm --list_systems.

**Comment by waorb** [comment]
hdblcm --list_systems would catch already installed HANA systems, but I thought the main purpose of this playbook was to check whether the selected SID is already in use. There could be an installed NetWeaver or S/4 instance on the system. hdblcm wouldn't be able to catch that, but saphostctrl --function ListInstances would.
As current HANA or NetWeaver based systems won't run without the SAP hostagent, you can pretty much assume that if an SAP system is already installed, that /usr/sap/hostctrl/exe/saphostctrl is available.
The NIECONN_REFUSED error is typically occurs when the instance specific sapstartsrv process isn't running correctly. In such a case, you shouldn't be able to start or stop the HANA database either.
The SAP startup framework also relies on the content of a file called /usr/sap/sapservices. In that file, you find the startup command for each instance specific sapstartsrv process, including an update to the LD_LIBRARY_PATH environment variable.
So the entries in that file start with
LD_LIBRARY_PATH=/usr/sap/SID
and perhaps the easiest would be to just grep for an existing line like ^/LD_LIBRARY_PATH=/usr/sap/SID in /usr/sap/sapservices.

**Comment by rhmk** [comment]
I came across an additional wrong assumption. The hana_exists fails, when the sidadm user is existing. This can be by intention, as an enterprise may add the user in a directory service prior to the installation to ensure proper central usermanagement.
I suggest moving that to a uid/gid detection and setting the proper variables, and fail if there is a conflict between global/local setting of the users
